import { Lightbulb, Sparkles } from "lucide-react";
import { cn } from "@/lib/utils";

/** AI-written explanation and exam tip. Always labelled as AI-generated —
 *  a learner should know which words came from a model, not from the person
 *  who curated the bank. */
export function AiInsight({
  explanation,
  tip,
  className,
}: {
  explanation: string | null;
  tip: string | null;
  className?: string;
}) {
  if (!explanation && !tip) return null;

  return (
    <div
      className={cn("rounded-xl border border-accent-fill/25 bg-accent-soft/50 p-3.5", className)}
      data-testid="ai-insight"
    >
      <p className="flex items-center gap-1.5 text-[11px] font-semibold tracking-[0.12em] text-accent-soft-ink uppercase">
        <Sparkles className="size-3.5" aria-hidden />
        AI explanation
      </p>
      {explanation && (
        <p className="mt-2 text-sm leading-relaxed text-ink">{explanation}</p>
      )}
      {tip && (
        <p className="mt-2.5 flex items-start gap-2 rounded-lg bg-surface/70 px-3 py-2 text-sm leading-relaxed text-ink">
          <Lightbulb className="mt-0.5 size-4 shrink-0 text-warn" aria-hidden />
          <span>
            <span className="font-medium">Tip: </span>
            {tip}
          </span>
        </p>
      )}
      <p className="mt-2 text-[11px] text-muted">
        Generated by AI — double-check anything that surprises you.
      </p>
    </div>
  );
}
